Added the dodolist file for review.
addisalemseifu/CodeReviewOntodolist pull request #1
Opened 2023-04-03 10:52 UTC by addisalemseifu

-Copy all the documents from the todo list file.

2023-04-03 12:36 UTC, Amazinggracee commented
> -Copy all the documents from the to-do list file.

Hey, Addisalemseifu, It  would be nice if you make your PR more descriptive, for example

- [ ]  I gave feedback on someone else's project based on clean code best practices.

- [ ]  I applied the knowledge gained in the past when giving a code review.

2023-04-03 12:52 UTC, Amazinggracee requested changes
### Highlights
![196425615-8927e377-c543-407b-8da4-5c09fecc261b](https://user-images.githubusercontent.com/107859883/229514525-8e23ea47-0e1c-42d0-aaa7-9543c9dd5dee.gif)

- [ ] All linter checks are passing ✔️ ✔️
- [ ] Your project works as expected and is interactive 👏 👏
Optional suggestions
OPTIONAL- After clearing all completed task, the index for the tasks do not reset, please fix this 🙏
Your project: :recycle:

2023-04-03 12:52 UTC, Amazinggracee commented on src/index.html
> +            </div>
Nice work dear, kindly close-up the blank lines, spaces, or indentations unless it is to separate large or logical code blocks.

2023-04-03 12:52 UTC, Amazinggracee commented on src/index.css
> +  cursor: pointer;
To keep your code simple, kindly avoid duplicated code. Please check your lines 82, 58, etc.

2023-04-03 13:34 UTC, addisalemseifu commented on src/index.css
> +  cursor: pointer;
Thanks for the comment. I will fix that right away.

2023-04-04 12:42 UTC, Amazinggracee approved these changes
### Approved
![unnamed](https://user-images.githubusercontent.com/107859883/229794846-64d98097-4d6a-4584-986a-98b6c0303f23.gif)
Nothing more to change, you can merge branch.

2023-04-04 13:45 UTC, merged

2023-04-07 12:47 UTC, addisalemseifu commented
hey i am waiting for you.


On Tue, Apr 4, 2023 at 3:42 PM AMARACHI DIMKPA ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> Approved
>
> [image: unnamed]
> <https://user-images.githubusercontent.com/107859883/229794846-64d98097-4d6a-4584-986a-98b6c0303f23.gif>
> Nothing more to change, you can merge branch.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/addisalemseifu/CodeReviewOntodolist/pull/1#pullrequestreview-1370892816>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APW72WDTZ2ZW4NPWSFP2TI3W7QJNHANCNFSM6AAAAAAWRERMSU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>